version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - psql
    environment:
      - DATABASE_HOST=psql
      - DATABASE_USERNAME=me
      - DATABASE_PASSWORD=its_really_me
  psql:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=its_really_me
    ports:
      - "5432:5432"
