# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 302d3aedb94ebb7b728a5ce64a5c96541f585d269c9f46288cfe9a9360b9030807dc7d1c021a753033f38328c1fbb3f15e9261a1fe6969bff1f8e77895445598

test:
  secret_key_base: d16122744877323860372f35f4bf851e400cd5a2940382cc83627d68431df0bfef5224d5cbf4ed48e8df82617b77b666127cccb1c3424377fba405c79d4b6a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
